### PR TITLE
Add Line.color setter/getter

### PR DESCRIPTION
**Pull request by CedarGroveStudios**
Allows line color to be changed after instantiation using the Line `color` property rather than the hidden Polygon `outline` property.

### CODE REVIEW

**Review by ladyada — APPROVED** [review]
ddidnt test but looks ok!

**Comment by CedarGroveStudios** [comment]
@ladyada Thanks! I tested it thoroughly with v7.0. Needed it for an HP-35 led display graphics widget:

Screen Shot 2021-11-19 at 10 36 42 AM

**Comment by ladyada** [comment]
oooh that is so adorable~!

**Comment by CedarGroveStudios** [comment]
Thanks @ladyada. I'm working on this set of scalable, stackable, display-independent widgets: 10-segment bar graph, HP-35 4-digit bubble display, neopixels, animated dual load cell scale, and 6E5 magic-eye tuning indicator. Planning to add a clock and a couple of 90-degree and edge-view panel meter objects soon.

widgets_catalog_2021-11-19

**Pull request merged**
