### PR TITLE
Update circle.py

### PR DESCRIPTION
**Pull request by empirical-dan**
Added x0, y0, the co-ordinates of the centre of the circle. Only r, radius added to Circle object to save space. Properties added for x0, y0. Setters also added so that the Circle object can be moved with reference to its center.

### CODE REVIEW

**Comment by kmatch98** [comment]
Awesome.  The code changes look great!  

For future reference, to avoid closing and creating a new issue, you can commit and push changes to the same branch `patch-1` and those changes will be applied to any open pull request that you have.  

Anyway, the code is failing due to "black" formatting.  I fetched your code and ran "black" on it.  You should see a pull request on your `patch-2` branch.  If you accept and merge that pull request, it should make it pass the "Build CI/test" and get a green check mark.  

If you run into issues, just add a note here.  Thanks for taking the time to work through your first pull request.  I know it's a little daunting to learn all these new system, but it gives a way for folks to collaborate (even if some steps are painful and/or confusing).  Thanks a lot!

**Comment by kmatch98** [comment]
You got a green check!  

Thanks for working through this.  

This looks good to me and ready for review.

**Comment by empirical-dan** [comment]
> You got a green check!
> 
> Thanks for working through this.
> 
> This looks good to me and ready for review.

Thank you for guiding me through the process!

**Comment by jposada202020** [comment]
Will Take a look tonight @empirical-dan @kmatch98 Just for completion purposes :)
Thanks @empirical-dan for your contribution feel free to ask questions you can find us in Adafruit Discord if needed.
Thank you again for contributing and making your first PR to CircuitPython. it is awesome.... 🚀

**Comment by jposada202020** [comment]
I tested this on works as expected.

```python
Adafruit CircuitPython 6.2.0-beta.4 on 2021-03-18; Adafruit PyPortal Titano with samd51j20
```

**Review by jposada202020 — APPROVED** [review]
I test this using the Pyportal as mentioned in the comments. works as expected

**Comment by kmatch98** [comment]
Thanks for the review @jposada202020.

@empirical-dan Many congratulations on your first Pull Request!  Thanks for taking time to do this!

**Comment by ladyada** [comment]
🍰

**Comment by empirical-dan** [comment]
Thanks both!

**Pull request merged**
