### PR TITLE
Add magtag example

### PR DESCRIPTION
**Pull request by FoamyGuy**
This adds an example script that is adapted to work on the magtag. Here is how it looks:
image

### CODE REVIEW

**Review by ladyada — APPROVED** [review]

**Comment by ladyada** [comment]
dya wanna add some grayscale?

**Comment by FoamyGuy** [comment]
@ladyada I can do that, I tried a few color values and couldn't get any grays to show up. Maybe I need to build from that recent PRs branch? I'll give that a try.

**Comment by FoamyGuy** [comment]
That seemed to do the trick:
image

**Comment by ladyada** [comment]
woohoo!

**Pull request merged**
